import type { ComponentType, SVGProps } from "react";
import {
  Wifi,
  Car,
  Utensils,
  Coffee,
  Dumbbell,
  Waves,
  Sparkles,
  Tv,
  Snowflake,
  Bath,
  Wind,
  Bell,
  ConciergeBell,
  PawPrint,
  Cigarette,
  CigaretteOff,
  Baby,
  Accessibility,
  ShieldCheck,
  Camera,
  Building2,
  TreePine,
  Sun,
  Mountain,
  Anchor,
  PartyPopper,
  Briefcase,
  Users,
  PlaneTakeoff,
  ParkingCircle,
  Beer,
  WashingMachine,
  Bike,
  Umbrella,
  Soup,
  GlassWater,
  Bed,
  Flower2,
  Phone,
  Tag,
  Tent,
  Lock,
  CheckCircle,
} from "lucide-react";

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

// Match amenity names (case-insensitive, partial) to a lucide icon.
// Order matters: more specific terms come first so "non smoking" beats "smoking".
const RULES: Array<{ test: RegExp; icon: IconComponent }> = [
  { test: /wi-?fi|internet|wireless/i, icon: Wifi },
  { test: /non[-\s]?smoking|smoke[-\s]?free/i, icon: CigaretteOff },
  { test: /smoking/i, icon: Cigarette },
  { test: /pet|dog|cat/i, icon: PawPrint },
  { test: /child|kid|family|baby/i, icon: Baby },
  { test: /accessib|wheelchair|disabled/i, icon: Accessibility },
  { test: /pool|swimming|jacuzzi|hot tub/i, icon: Waves },
  { test: /spa|massage|wellness|sauna|hammam|steam/i, icon: Sparkles },
  { test: /gym|fitness|workout/i, icon: Dumbbell },
  { test: /restaurant|dining|kitchen|food/i, icon: Utensils },
  { test: /breakfast/i, icon: Coffee },
  { test: /coffee|cafe|tea/i, icon: Coffee },
  { test: /bar|lounge|pub/i, icon: Beer },
  { test: /buffet|meal|dinner|lunch/i, icon: Soup },
  { test: /minibar|mini-bar|drinks|beverage/i, icon: GlassWater },
  { test: /tv|television|cable|netflix/i, icon: Tv },
  { test: /air[-\s]?con|a\/c|ac\b|cooling/i, icon: Snowflake },
  { test: /heating|heater|warm/i, icon: Wind },
  { test: /bath|shower|hairdryer|toilet/i, icon: Bath },
  { test: /laundry|washing|dry[-\s]?clean/i, icon: WashingMachine },
  { test: /parking|garage|valet/i, icon: ParkingCircle },
  { test: /shuttle|transfer|airport/i, icon: PlaneTakeoff },
  { test: /car[-\s]?rental|car hire|taxi/i, icon: Car },
  { test: /bike|bicycle|cycling/i, icon: Bike },
  { test: /beach|seaside|coast/i, icon: Umbrella },
  { test: /sea|ocean|harbor|marina|boat/i, icon: Anchor },
  { test: /garden|park|terrace|patio/i, icon: TreePine },
  { test: /mountain|hill|view/i, icon: Mountain },
  { test: /sun|outdoor|solarium|deck/i, icon: Sun },
  { test: /flower|botanic/i, icon: Flower2 },
  { test: /tour|excursion|sightseeing|trip/i, icon: Tent },
  { test: /event|wedding|party|celebration/i, icon: PartyPopper },
  { test: /business|conference|meeting|workspace/i, icon: Briefcase },
  { test: /group|community|social/i, icon: Users },
  { test: /reception|24[-\s]?hour|front[-\s]?desk/i, icon: Bell },
  { test: /concierge|service|attendant|butler/i, icon: ConciergeBell },
  { test: /security|safe|cctv|surveillance/i, icon: ShieldCheck },
  { test: /camera|photo|photography/i, icon: Camera },
  { test: /lock|locker|storage|baggage|luggage/i, icon: Lock },
  { test: /elevator|lift|building|hotel/i, icon: Building2 },
  { test: /room|bed|linen|pillow/i, icon: Bed },
  { test: /phone|call|telephone/i, icon: Phone },
  { test: /discount|offer|promo|deal/i, icon: Tag },
];

export function pickAmenityIcon(name: string): IconComponent {
  for (const rule of RULES) {
    if (rule.test.test(name)) return rule.icon;
  }
  return CheckCircle;
}
