import type { Metadata, Viewport } from 'next';
import { Inter, Poppins } from 'next/font/google';
import { SITE } from '@/shared/lib/seo';
import Analytics from './Analytics';
import '../styles/index.css';

// Self-hosted, non-render-blocking webfonts (replaces the old render-blocking
// Google Fonts @import). `display: swap` paints text immediately in the
// fallback, then swaps — no invisible-text delay. Exposed as CSS variables so
// styles can opt in; Inter is the document default.
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
  display: 'swap',
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

// Site-wide metadata defaults. Per-route values (title, description, canonical,
// OG, hreflang, robots) are produced by generateMetadata in [[...slug]]/page.tsx
// and override these. Favicon + OG/Twitter images are generated by the
// app/icon.tsx and app/opengraph-image.tsx file conventions — do NOT hardcode
// links to /favicon.ico etc. here (those files don't exist).
export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: 'Book United Hotels | Hotels in Istanbul & Turkey — B2B & B2C',
    template: '%s | Book United Hotels',
  },
  description:
    'Book verified hotels across Istanbul and Turkey at direct rates. Bosphorus-view suites, boutique Sultanahmet stays, plus B2B wholesale rates for travel agents.',
  applicationName: SITE.name,
  manifest: '/site.webmanifest',
  alternates: { canonical: '/' },
  formatDetection: { telephone: true, address: true, email: false },
  category: 'travel',
  robots: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  // Optional: set NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION to add the GSC meta tag.
  verification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION }
    : undefined,
  openGraph: {
    type: 'website',
    siteName: SITE.name,
    url: SITE.url,
    locale: SITE.locale,
  },
  twitter: { card: 'summary_large_image' },
};

export const viewport: Viewport = {
  themeColor: '#0B1F3B',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body style={{ fontFamily: 'var(--font-inter), system-ui, -apple-system, sans-serif' }}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
